import { Inter } from "next/font/google";
import "../styles/main.css";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
 
import { ourFileRouter } from "./api/uploadthing/core";
import Providers from "@/context/Providers";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
     
      <Providers>
      
      <NextSSRPlugin
       routerConfig={extractRouterConfig(ourFileRouter)}
        />
      {children}
      </Providers>
      </body>
    </html>
  );
}
